### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rdmrm4g00** [michaeldfallen/kcal#2]
Hey,

Awesome project I wanna try this out in our little IT room for the guys.

How do you format the credentials.conf?

I'm totally stuck - just want to test with one room?

Thanks

Ross

**Comment by michaeldfallen** [comment]
Hi, thanks very much. 

Tbh it's been a while since I last used this but I think the file format is:

**conf/credentials.conf**
```
username: 'your username'
password: 'your password'
```

You can also export env vars named `OFFICE365_USER` and `OFFICE365_PASS` (mostly useful for when you deploy but it would work if the credentials.conf is breaking)

**Comment by rdmrm4g00** [comment]
I've got it ok now being a tool - now I get a Oops an error


Oops, an error occured
This exception has been logged with id 79jm9e5n9.


(Starting server. Type Ctrl+D to exit logs, the server will remain in background                                                    )

Play server process ID is 5406
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[error] application -

! @79jm9domg - Internal server error, for (GET) [/rooms/all/] ->

play.api.Application$$anon$1: Execution exception[[DecoderException: Illegal hex                                                    adecimal character m at index 0]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.t                                                    ypesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.t                                                    ypesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfu                                                    n$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.p                                                    lay_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfu                                                    n$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.p                                                    lay_2.10-2.3.4.jar:2.3.4]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.s                                                    cala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.codec.DecoderException: Illegal hexadecimal charac                                                    ter m at index 0
        at org.apache.commons.codec.binary.Hex.toDigit(Hex.java:178) ~[commons-c                                                    odec.commons-codec-1.9.jar:1.9]
        at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:89) ~[commons-                                                    codec.commons-codec-1.9.jar:1.9]
        at play.api.libs.Codecs$.hexStringToByte(Codecs.scala:76) ~[com.typesafe                                                    .play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.Crypto$.decryptAES(Crypto.scala:276) ~[com.typesafe.pla                                                    y.play_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.Crypto$.decryptAES(Crypto.scala:252) ~[com.typesafe.pla                                                    y.play_2.10-2.3.4.jar:2.3.4]
[error] application -

! @79jm9e5n9 - Internal server error, for (GET) [/rooms/upperCrescent/] ->

play.api.Application$$anon$1: Execution exception[[DecoderException: Illegal hex                                                    adecimal character m at index 0]]
        at play.api.Application$class.handleError(Application.scala:296) ~[com.t                                                    ypesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.DefaultApplication.handleError(Application.scala:402) [com.t                                                    ypesafe.play.play_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfu                                                    n$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [com.typesafe.play.p                                                    lay_2.10-2.3.4.jar:2.3.4]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfu                                                    n$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [com.typesafe.play.p                                                    lay_2.10-2.3.4.jar:2.3.4]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.s                                                    cala:33) [org.scala-lang.scala-library-2.10.4.jar:na]
Caused by: org.apache.commons.codec.DecoderException: Illegal hexadecimal charac                                                    ter m at index 0
        at org.apache.commons.codec.binary.Hex.toDigit(Hex.java:178) ~[commons-c                                                    odec.commons-codec-1.9.jar:1.9]
        at org.apache.commons.codec.binary.Hex.decodeHex(Hex.java:89) ~[commons-                                                    codec.commons-codec-1.9.jar:1.9]
        at play.api.libs.Codecs$.hexStringToByte(Codecs.scala:76) ~[com.typesafe                                                    .play.play_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.Crypto$.decryptAES(Crypto.scala:276) ~[com.typesafe.pla                                                    y.play_2.10-2.3.4.jar:2.3.4]
        at play.api.libs.Crypto$.decryptAES(Crypto.scala:252) ~[com.typesafe.pla                                                    y.play_2.10-2.3.4.jar:2.3.4]


any idea?

really would like to use this for our IT room
